/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Primary entry point. Holds all Apple auth state for one account session. */
export declare class Session {
  /**
   * Create a new session.
   * - `data_dir`: directory for persistent storage (certs, anisette state, signing records)
   * - `anisette_url`: optional override for the anisette WebSocket server URL
   */
  constructor(dataDir: string, anisetteUrl?: string | undefined | null)
  /**
   * Login to Apple ID. The `two_fa_callback` is called when 2FA is required;
   * it must return the 6-digit code as a Promise<string>.
   */
  login(email: string, password: string, twoFaCallback: (err: Error | null, arg: TwoFaInfo) => any): Promise<void>
  getSessionInfo(): Promise<SessionInfo>
  listTeams(): Promise<Array<Team>>
  listCerts(teamId?: string | undefined | null): Promise<Array<Cert>>
  revokeCert(serialNumber: string, teamId?: string | undefined | null): Promise<void>
  listAppIds(teamId?: string | undefined | null): Promise<Array<AppId>>
  createAppId(bundleId: string, name: string, teamId?: string | undefined | null): Promise<AppId>
  listDevices(teamId?: string | undefined | null): Promise<Array<Device>>
  registerDevice(udid: string, name: string, teamId?: string | undefined | null): Promise<void>
  signApp(appPath: string, teamId?: string | undefined | null): Promise<string>
  installApp(appPath: string, udid: string, teamId?: string | undefined | null): Promise<void>
  listPhotos(udid: string, limit?: number | undefined | null, cursor?: string | undefined | null): Promise<ListPhotosPage>
  getPhotoInfo(udid: string, path: string): Promise<PhotoInfo>
  downloadPhoto(udid: string, remotePath: string, localDest: string): Promise<DownloadPhotoResult>
  pairDevice(udid: string): Promise<boolean>
  validatePairing(udid: string): Promise<boolean>
}

export interface AppId {
  appIdId: string
  name: string
  identifier: string
}

export interface Cert {
  serialNumber: string
  name: string
  expirationDate?: string
}

export interface ConnectedDevice {
  udid: string
  name: string
  productType: string
  productVersion: string
}

export interface Device {
  udid: string
  name: string
  status: string
}

export interface DownloadPhotoResult {
  dest: string
  bytesWritten: number
}

/** List USB-connected devices via usbmuxd. Does not require Apple auth. */
export declare export declare function listConnectedDevices(): Promise<Array<ConnectedDevice>>

export interface ListPhotosPage {
  photos: Array<string>
  nextCursor?: string
}

export interface PhotoInfo {
  size: number
  modified: number
}

/**
 * Capture a screenshot from a connected device. Does not require Apple auth.
 * Returns the output path where the screenshot was saved.
 */
export declare export declare function screenshot(udid: string, outputPath: string): Promise<string>

export interface SessionInfo {
  loggedIn: boolean
  email?: string
}

export interface Team {
  teamId: string
  name: string
  type: string
  status: string
}

export interface TwoFaInfo {
  type: string
}
