import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'

const _require = createRequire(import.meta.url)

// Types generated by napi-rs from Rust structs in src/types.rs
export type {
  ConnectedDevice,
  Team,
  Cert,
  AppId,
  Device,
  SessionInfo,
  ListPhotosPage,
  PhotoInfo,
  DownloadPhotoResult,
  TwoFaInfo,
} from '../../dist/index'

import type {
  ConnectedDevice,
  Team,
  Cert,
  AppId,
  Device,
  SessionInfo,
  ListPhotosPage,
  PhotoInfo,
  DownloadPhotoResult,
} from '../../dist/index'

export interface StoredSession {
  email: string
  token: string
  duration: number
  expiry: number
  adsid: string
}

export interface NativeSession {
  getSessionData(): Promise<StoredSession | null>
  restoreSession(data: StoredSession): Promise<boolean>
  logout(): Promise<void>
  submitTwoFa(code: string): Promise<void>
  login(
    email: string,
    password: string,
    twoFaCallback: (info: { type: string }) => void
  ): Promise<void>
  getSessionInfo(): Promise<SessionInfo>
  listTeams(): Promise<Team[]>
  listCerts(teamId?: string | null): Promise<Cert[]>
  revokeCert(serialNumber: string, teamId?: string | null): Promise<void>
  listAppIds(teamId?: string | null): Promise<AppId[]>
  createAppId(
    bundleId: string,
    name: string,
    teamId?: string | null
  ): Promise<AppId>
  listDevices(teamId?: string | null): Promise<Device[]>
  registerDevice(
    udid: string,
    name: string,
    teamId?: string | null
  ): Promise<void>
  signApp(appPath: string, teamId?: string | null): Promise<string>
  installApp(
    appPath: string,
    udid: string,
    teamId?: string | null
  ): Promise<void>
  listPhotos(
    udid: string,
    limit?: number | null,
    cursor?: string | null
  ): Promise<ListPhotosPage>
  getPhotoInfo(udid: string, path: string): Promise<PhotoInfo>
  downloadPhoto(
    udid: string,
    remotePath: string,
    localDest: string
  ): Promise<DownloadPhotoResult>
  pairDevice(udid: string): Promise<boolean>
  validatePairing(udid: string): Promise<boolean>
}

export type NativeSessionConstructor = new (
  dataDir: string,
  anisetteUrl?: string | null
) => NativeSession

export interface NativeAddon {
  Session: NativeSessionConstructor
  listConnectedDevices(): Promise<ConnectedDevice[]>
  screenshot(udid: string, outputPath: string): Promise<string>
  launchApp(udid: string, bundleId: string): Promise<number>
  launchAppWithEnv(
    udid: string,
    bundleId: string,
    envVars: Record<string, string> | null
  ): Promise<number>
  startTunnel(udid: string, remotePort: number): Promise<number>
  stopTunnel(localPort: number): Promise<void>
  startXcuitest(
    udid: string,
    bundleId: string,
    testRunnerBundleId: string,
    env?: Record<string, string>
  ): Promise<number>
  stopXcuitest(sessionId: number): Promise<void>
  listInstalledApps(
    udid: string,
    appType?: string | null
  ): Promise<InstalledAppInfo[]>
}

export interface InstalledAppInfo {
  bundleId: string
  bundleName: string | null
  bundleExecutable: string | null
}

let _native: NativeAddon | null = null

/**
 * Load the napi-rs generated native addon.
 * The @napi-rs/cli build command places `index.js` (a platform-aware loader)
 * at the package root alongside the platform `.node` file.
 */
export function getNative(): NativeAddon {
  if (_native) return _native
  // Package root is two levels up from ts/isideload/
  const pkgRoot = join(dirname(import.meta.dirname!), '..')
  _native = _require(join(pkgRoot, 'dist', 'index.js')) as NativeAddon
  return _native
}
