#!/bin/bash
set -e
if systemctl is-active --quiet tachibana-server.service; then
    systemctl stop tachibana-server.service
fi
systemctl disable tachibana-server.service || true
systemctl daemon-reload
